### PR TITLE
Fixes for HCI

### PR DESCRIPTION
**Pull request by micprog**

### CODE REVIEW

**Comment by yvantor** [comment]
@FrancescoConti remember this one

**Review by yvantor — APPROVED** [review]
Approved.

**Review by FrancescoConti — APPROVED** [review]

**Comment by yvantor** [comment]
@FrancescoConti I think you are the only one allowed for merging.

**Comment by FrancescoConti** [comment]
Am I? I have the rights, but I am not the maintainer of `cluster_interconenct`. I will do it but I do not want to overstep anyone

**Pull request merged**
